routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::controller(WelcomeController::class)->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    Route::get('product/{slug}', 'product')->name('product');
    Route::get('shop', 'shop')->name('shop');
    Route::post('product/variation-info', 'variation')->name('product.variation');
});
Route::namespace('App\Http\Controllers')->group(function () {

    Route::get('admin/login', 'Auth\LoginController@loginForm')->name('login');
    Route::post('securelogin', 'Auth\LoginController@login')->name('securelogin');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => ['auth']], function () {
        Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');

            // Setting Routes
            Route::get('/setting', 'SettingController@index')->name('setting');
            Route::post('/setting/update', 'SettingController@update')->name('setting.update');
            // Setting Routes end

            //  Users Route
            Route::name('users.')->prefix('users')->group(function () {
                Route::get('/', 'UserController@index')->name('index');
                Route::get('/customer', 'UserController@customer')->name('customer');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/', 'UserController@store')->name('store');
                Route::get('/{id}/show', 'UserController@show')->name('show');
                Route::get('/{id}/edit', 'UserController@edit')->name('edit');
                Route::patch('/{id}', 'UserController@update')->name('update');
                Route::get('/delete/{id}', 'UserController@destroy')->name('destroy');
            });
            //  Users Route End

            Route::name('slider.')->prefix('slider')->group(function () {
                Route::get('/', 'SliderController@index')->name('index');
                Route::post('/set_order', 'SliderController@set_order')->name('order');
                Route::post('/store', 'SliderController@store')->name('store');
                Route::get('/edit/{id}', 'SliderController@edit')->name('edit');
                Route::post('/update/{id}', 'SliderController@update')->name('update');
                Route::get('/delete/{id}', 'SliderController@destroy')->name('destroy');
            });

            Route::name('category.')->prefix('category')->group(function () {
                Route::get('/', 'CategoryController@index')->name('index');
                Route::post('/set_order', 'CategoryController@set_order')->name('order');
                Route::post('/store', 'CategoryController@store')->name('store');
                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('/update/{id}', 'CategoryController@update')->name('update');
                Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
            });

            Route::name('brand.')->prefix('brand')->group(function () {
                Route::get('/', 'BrandController@index')->name('index');
                Route::post('/set_order', 'BrandController@set_order')->name('order');
                Route::post('/store', 'BrandController@store')->name('store');
                Route::get('/edit/{id}', 'BrandController@edit')->name('edit');
                Route::post('/update/{id}', 'BrandController@update')->name('update');
                Route::get('/delete/{id}', 'BrandController@destroy')->name('destroy');
            });

            // Size Chart
            Route::name('sizechart.')->prefix('sizechart')->group(function () {
                Route::get('/', 'SizeChartController@index')->name('index');
                Route::post('/set_order', 'SizeChartController@set_order')->name('order');
                Route::post('/store', 'SizeChartController@store')->name('store');
                Route::get('/edit/{id}', 'SizeChartController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeChartController@update')->name('update');
                Route::get('/delete/{id}', 'SizeChartController@destroy')->name('destroy');
            });
            // Size chart end

            // Size
            Route::name('size.')->prefix('size')->group(function () {
                Route::get('/', 'SizeController@index')->name('index');
                Route::post('/set_order', 'SizeController@set_order')->name('order');
                Route::post('/store', 'SizeController@store')->name('store');
                Route::get('/edit/{id}', 'SizeController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeController@update')->name('update');
                Route::get('/delete/{id}', 'SizeController@destroy')->name('destroy');
            });
            // Size ends

            Route::name('product.')->prefix('product')->group(function () {
                Route::get('/', 'ProductController@index')->name('index');
                Route::get('/create', 'ProductController@create')->name('create');
                Route::post('/store', 'ProductController@store')->name('store');
                Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
                Route::patch('/update/{id}', 'ProductController@update')->name('update');
                Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
                Route::post('/update/status', 'ProductController@status')->name('status');
                Route::post('/update/featured', 'ProductController@featured')->name('featured');
                Route::get('/delete-image/{albumName}/{photoName}', 'ProductController@delete_gallery_image');

                Route::name('variation.')->group(function () {
                    Route::get('/color-and-sizes/{slug}', 'ProductController@variation')->name('index');
                    Route::get('/add-color-and-sizes/{slug}', 'ProductController@addVariationForm')->name('create');
                    Route::post('/add-color-and-sizes/{slug}', 'ProductController@addVariation')->name('store');
                    Route::get('/edit-color-and-sizes/{slug}/{id}', 'ProductController@editVariation')->name('edit');
                    Route::patch('/update-color-and-sizes/{slug}/{id}', 'ProductController@updateVariation')->name('update');
                    Route::get('/color-and-sizes/{slug}/delete/{id}', 'ProductController@deleteVariation')->name('delete');
                    Route::get('/delete-variation-image/{id}/{photoName}', 'ProductController@delete_variation_image');
                });
            });

            Route::name('faq.')->prefix('faq')->group(function () {
                Route::get('/', 'FaqController@index')->name('index');
                Route::post('/set_order', 'FaqController@set_order')->name('order');
                Route::post('/store', 'FaqController@store')->name('store');
                Route::get('/edit/{id}', 'FaqController@edit')->name('edit');
                Route::post('/update/{id}', 'FaqController@update')->name('update');
                Route::get('/delete/{id}', 'FaqController@destroy')->name('destroy');
            });

            Route::name('blog.')->prefix('blog')->group(function () {
                Route::get('/', 'BlogController@index')->name('index');
                Route::get('/create', 'BlogController@create')->name('create');
                Route::post('/store', 'BlogController@store')->name('store');
                Route::get('/edit/{id}', 'BlogController@edit')->name('edit');
                Route::post('/update/{id}', 'BlogController@update')->name('update');
                Route::get('/delete/{id}', 'BlogController@destroy')->name('destroy');
                Route::post('/update/status', 'BlogController@status')->name('status');
            });

            Route::get('/terms-and-condition', 'TermsController@index')->name('terms');
            Route::post('/terms-and-condition/update', 'TermsController@update')->name('terms.update');

            Route::get('/policy', 'PolicyController@index')->name('policy');
            Route::post('/policy/update', 'PolicyController@update')->name('policy.update');
        });
    });
});

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    protected function createSlug($title, $id = 0)
    {
        // Normalize the title
        $slug = str_slug($title);

        $allSlugs = $this->getRelatedSlugs($slug, $id);

        // If we haven't used it before then we are all good.
        if (!$allSlugs->contains('slug', $slug)) {
            return $slug;
        }

        // Just append numbers like a savage until we find not used.
        for ($i = 1; $i <= 10; $i++) {
            $newSlug = $slug . '-' . $i;
            if (!$allSlugs->contains('slug', $newSlug)) {
                return $newSlug;
            }
        }

        throw new \Exception('Can not create a unique slug');
    }
    protected function getRelatedSlugs($slug, $id = 0)
    {
        return Category::select('slug')->where('slug', 'like', $slug . '%')
            ->where('id', '<>', $id)
            ->get();
    }
}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Brand;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use Illuminate\Support\Facades\DB;
use Intervention\Image\Facades\Image;

class BrandController extends Controller
{
    public function index(){
        $brands = Brand::orderBy('order_item')->get();
        return view('admin.brand.index', compact('brands'));
    }
    
    public function set_order(Request $request)
    {
        $list_order = [];
        $list_order = $request['list_order'];
        $i = 1;
        foreach ($list_order as $id) {
            $updateData = array("order_item" => $i);
            Brand::where('id', $id)->update($updateData);
            $i++;
        }
        $data = array('status' => 'success');
        echo json_encode($data);
    }

    public function create(){
        return view('admin.brand.form');
    }

    public function store(Request $request){
        $this->validate($request,[
            'title' => 'required'
        ]);

        $brand = new Brand();
        $brand->title = $request->title;
        $slug = Brand::createSlug($request->title, 'id', 0);
        $brand->slug = $slug;
        $max_order = DB::table('brands')->max('order_item');
        $brand->order_item = $max_order + 1;
        $path = public_path() . '/storage/brand/';
        $folderPath = 'public/brand/';
        if (!file_exists($path)) {
            Storage::makeDirectory($folderPath, 0777, true, true);
        }

        if ($request->hasFile('image')) {
            $validatedData = $request->validate([
                'image' => 'image|mimes:jpeg,png,jpg|max:50000',
            ]);
            $file = $request->file('image');
            $fileName = time() . '.webp';
            
            $cover = storage_path('app/' . $folderPath. $fileName);
            Image::make($file)->encode('webp')->save($cover);
            // Storage::putFileAs($folderPath, new file($file), $fileName);
            $brand->image = $fileName;
        }
        $brand->save();
        // for($i=1; $i < 5; $i++){
        //     $banner = new BrandBanner();
        //     $banner->brand_id = $brand->id;
        //     $banner->title = $i;
        //     $banner->order_item = $i;
        //     $banner->save();
        // }
        return redirect(route('admin.brand.index'))->with('status', 'Brand created successfully');
    }

    public function edit($id){
        $brand = Brand::findOrFail(base64_decode($id));
        return view('admin.brand.form')->with('brand', $brand);
    }

    public function update(Request $request, $id){
        $this->validate($request,[
            'title' => 'required'
        ]);

        $brand = Brand::findOrFail(base64_decode($id));
        if($brand->title != $request->title){
            $slug = Brand::createSlug($request->title, 'id', 0);
        }else{
            $slug = $brand->slug;
        }
        $brand->title = $request->title;
        $brand->slug = $slug;
        $path = public_path() . '/storage/brand/';
        $folderPath = 'public/brand/';
        if (!file_exists($path)) {
            Storage::makeDirectory($folderPath, 0777, true, true);
        }

        if ($request->hasFile('image')) {
            $validatedData = $request->validate([
                'image' => 'image|mimes:jpeg,png,jpg|max:50000',
            ]);
            $oldImage = $brand->image;
            $file = $request->file('image');
            $fileName = time() . '.webp';
            
            $cover = storage_path('app/' . $folderPath. $fileName);
            Image::make($file)->encode('webp')->save($cover);

            // Storage::putFileAs($folderPath, new file($file), $fileName);
            $brand->image = $fileName;
            if(isset($oldImage)){
                Storage::delete('public/brand/' . $oldImage);
            }
        }
        $brand->update();
        return redirect(route('admin.brand.index'))->with('status', 'Brand updated successfully');
    }

    public function destroy($id){
        $brand = Brand::findOrFail(base64_decode($id));
        if(isset($brand->image)){
            Storage::delete('public/brand/' . $brand->image);
        }

        $brand->delete();
        return redirect()->back()->with('status', 'Brand deleted successfully');
    }
}

resources/views/admin/brand/form.blade.php
@extends('admin/layouts.headersidebar')
@section('style')
    <link rel="stylesheet" href="{{ asset('backend/assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css') }}">
@endsection
@section('content')

    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>Brands</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.brand.index') }}">Brands</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{ isset($brand) ? 'Update' : 'Create' }}</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ route('admin.brand.index') }}" class="btn btn-sm btn-primary" title=""><i
                                class="fa fa-list"></i> Show Brands</a>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-12">
                @php
                    $url = route('admin.brand.store');
                if (isset($brand)){
                    $url = route('admin.brand.update', base64_encode($brand->id));
                }
                @endphp
                <form method="POST" action="{{ $url }}" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="body">
                            <div class="row">

                            <div class="col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default"><i
                                        class="fa fa-text-width fa-lg"></i> &nbsp;Title</span>
                                    </div>
                                    <input type="text" name="title" class="form-control"
                                            aria-label="Default" value="{{ isset($brand) ? $brand->title : '' }}"
                                            aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                            
                            <div class="col-md-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Image</span>
                                    </div>
                                    <input type="file" class="form-control" name="image">
                                    <label class="badge badge-warning pt-2">Image Size Must be 170 X 100
                                        Px</label>
                                </div>
                                @if(isset($brand))
                                <div style="float: right">
                                    @php($image = isset($brand->image) && $brand->image ? asset('storage/brand/'.$brand->image): '')     
                                    <img src="{{$image}}" alt="" class="image-responsive"
                                         style="width: 50px; height: 50px;">
                                </div>
                                @endif
                            </div>

                                                   
                            </div>
                            <div class="card-footer">
                                <a href="{{ route('admin.brand.index') }}" class="btn btn-danger">Cancel</a>
                                <span class="float-right">
                                <button type="submit" name="submit" class="btn btn-success" value="save">Save</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
<script src="https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script>
        CKEDITOR.replace( 'ckeditor' );
</script>
@endsection

resources/views/admin/brand/index.blade.php
@extends('admin/layouts.headersidebar')
@section('style')
    <link rel="stylesheet" href="{{ asset('backend/assets/vendor/nestable/jquery-nestable.css') }}"/>
    <link rel="stylesheet" href="{{ asset('backend/assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css') }}">
@endsection
@section('content')
    <script>
        $(document).ready(function () {
            var updateOutput = function (e) {
                var list = e.length ? e : $(e.target), output = list.data('output');

                $.ajax({
                    method: "POST",
                    url: "{{route('admin.brand.order')}}",
                    data: {
                        '_token': $('input[name=_token]').val(),
                        list_order: list.nestable('serialize'),
                        table: "brands"
                    },
                    success: function (response) {
                        console.log("success");
                        console.log("response " + response);
                        var obj = jQuery.parseJSON(response);
                        if (obj.status == 'success') {
                            swal({
                                title: 'Success!',
                                buttonsStyling: false,
                                confirmButtonClass: "btn btn-success",
                                html: '<b>Category</b> Sorted Successfully',
                                timer: 1000,
                                type: "success"
                            }).catch(swal.noop);
                        }
                        ;

                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    sweetAlert('Failure', 'Something Went Wrong!', 'error');
                });
            };

            $('#nestable').nestable({
                group: 1,
                maxDepth: 3,
            }).on('change', updateOutput);
        });
    </script>

    <?php
    function displayList($brands)
    {
    ?>
    <ol class="dd-list">
        <?php foreach ($brands as $item): ?>
        <li class="dd-item dd3-item" data-id="{{ $item->id }} ">
            <div class="dd-handle dd3-handle"></div>
            <div class="dd3-content">
                <small>
                    <b>{{ $item->title }}</b>
                </small>
                <span class="content-right">
                    <a href="{{ route('admin.brand.edit', base64_encode($item->id)) }}"
                        class="btn btn-sm btn-outline-primary" title="Edit"><i class="fa fa-edit"></i></a>
                    <a href="#delete"
                        data-toggle="modal"
                        data-id="{{ base64_encode($item->id) }}"
                        id="delete{{ base64_encode($item->id) }}"
                        class="btn btn-sm btn-outline-danger center-block"
                        onClick="delete_menu('{{ base64_encode($item->id) }}')"><i class="fa fa-trash  "></i></a>
                </span>
            </div>
        </li>
        <?php
        endforeach; ?>
    </ol>
    <?php
    }
    ?>

    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Brands</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item active" aria-current="page"> Manage your brands</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ url('admin') }}" class="btn btn-outline-primary btn-round"><i
                                class="fa fa-angle-double-left"></i> Go Back</a>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12">

                <ul class="nav nav-tabs">
                    <li class="nav-item"><a class="nav-link show  active" data-toggle="tab" href="#Pages">All
                            Brands</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#addPage">Add Brand</a></li>
                </ul>
                <div class="tab-content mt-0">
                    <div class="tab-pane show active" id="Pages">
                        <div class="card">
                            <div class="header card-header">
                                <h6 class="title mb-0">All Brands</h6>
                            </div>
                            <div class="body mt-0">
                                <div class="dd nestable-with-handle" id="nestable">
                                    <?php isset($brands) ? displayList($brands) : '' ?>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="addPage">
                        <div class="card">
                            <div class="header card-header">
                                <h6 class="title mb-0">Add Brand</h6>
                            </div>
                            <div class="body mt-2">
                                <form method="post" action="{{ route('admin.brand.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                    
                                        <div class="col-md-12">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text" id="inputGroup-sizing-default"><i
                                                    class="fa fa-text-width fa-lg"></i> &nbsp;Title</span>
                                                </div>
                                                <input type="text" name="title" class="form-control"
                                                       aria-label="Default"
                                                       aria-describedby="inputGroup-sizing-default">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text">Image</span>
                                                </div>
                                                <input type="file" class="form-control" name="image">
                                                <label class="badge badge-warning pt-2">Image Size Must be 170 X 100
                                                    Px</label>
                                            </div>
                                        </div>


                                        <div class="clearfix"></div>

                                        <div class="col-md-12">
                                            <a href="{{ route('admin.brand.index') }}"
                                               class="btn btn-outline-danger">Cancel</a>

                                            <button type="submit" style="float: right;" class="btn btn-outline-success">
                                                save
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>


            <div class="clearfix"></div>
            <div class="col-md-12">

            </div>

        </div>

        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog " role="document">
                <div class="modal-content bg-danger">
                    <div class="modal-header">
                        <h5 class="modal-title text-white" id="exampleModalLabel">Delete Brand</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-white">
                        <p>Are you Sure...!!</p>
                    </div>
                    <div class="modal-footer ">
                        <button type="button" class="btn btn-round btn-default" data-dismiss="modal">Close</button>
                        <a href="" class="btn btn-round btn-primary">Delete</a>
                    </div>
                </div>
            </div>
        </div>

    </div>


@endsection
@section('script')
    <script>

        function delete_menu(id) {
            var conn = './brand/delete/' + id;
            $('#delete a').attr("href", conn);
        }

    </script>
    <script src="{{ asset('backend/assets/vendor/nestable/jquery.nestable.js') }}"></script><!-- Jquery Nestable -->
    <script src="{{ asset('backend/html/assets/js/pages/ui/sortable-nestable.js') }}"></script>


@endsection