routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::controller(WelcomeController::class)->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    Route::get('product/{slug}', 'product')->name('product');
    Route::get('shop', 'shop')->name('shop');
    Route::post('product/variation-info', 'variation')->name('product.variation');
});
Route::namespace('App\Http\Controllers')->group(function () {

    Route::get('admin/login', 'Auth\LoginController@loginForm')->name('login');
    Route::post('securelogin', 'Auth\LoginController@login')->name('securelogin');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => ['auth']], function () {
        Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');

            // Setting Routes
            Route::get('/setting', 'SettingController@index')->name('setting');
            Route::post('/setting/update', 'SettingController@update')->name('setting.update');
            // Setting Routes end

            //  Users Route
            Route::name('users.')->prefix('users')->group(function () {
                Route::get('/', 'UserController@index')->name('index');
                Route::get('/customer', 'UserController@customer')->name('customer');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/', 'UserController@store')->name('store');
                Route::get('/{id}/show', 'UserController@show')->name('show');
                Route::get('/{id}/edit', 'UserController@edit')->name('edit');
                Route::patch('/{id}', 'UserController@update')->name('update');
                Route::get('/delete/{id}', 'UserController@destroy')->name('destroy');
            });
            //  Users Route End

            Route::name('slider.')->prefix('slider')->group(function () {
                Route::get('/', 'SliderController@index')->name('index');
                Route::post('/set_order', 'SliderController@set_order')->name('order');
                Route::post('/store', 'SliderController@store')->name('store');
                Route::get('/edit/{id}', 'SliderController@edit')->name('edit');
                Route::post('/update/{id}', 'SliderController@update')->name('update');
                Route::get('/delete/{id}', 'SliderController@destroy')->name('destroy');
            });

            Route::name('category.')->prefix('category')->group(function () {
                Route::get('/', 'CategoryController@index')->name('index');
                Route::post('/set_order', 'CategoryController@set_order')->name('order');
                Route::post('/store', 'CategoryController@store')->name('store');
                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('/update/{id}', 'CategoryController@update')->name('update');
                Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
            });

            Route::name('brand.')->prefix('brand')->group(function () {
                Route::get('/', 'BrandController@index')->name('index');
                Route::post('/set_order', 'BrandController@set_order')->name('order');
                Route::post('/store', 'BrandController@store')->name('store');
                Route::get('/edit/{id}', 'BrandController@edit')->name('edit');
                Route::post('/update/{id}', 'BrandController@update')->name('update');
                Route::get('/delete/{id}', 'BrandController@destroy')->name('destroy');
            });

            // Size Chart
            Route::name('sizechart.')->prefix('sizechart')->group(function () {
                Route::get('/', 'SizeChartController@index')->name('index');
                Route::post('/set_order', 'SizeChartController@set_order')->name('order');
                Route::post('/store', 'SizeChartController@store')->name('store');
                Route::get('/edit/{id}', 'SizeChartController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeChartController@update')->name('update');
                Route::get('/delete/{id}', 'SizeChartController@destroy')->name('destroy');
            });
            // Size chart end

            // Size
            Route::name('size.')->prefix('size')->group(function () {
                Route::get('/', 'SizeController@index')->name('index');
                Route::post('/set_order', 'SizeController@set_order')->name('order');
                Route::post('/store', 'SizeController@store')->name('store');
                Route::get('/edit/{id}', 'SizeController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeController@update')->name('update');
                Route::get('/delete/{id}', 'SizeController@destroy')->name('destroy');
            });
            // Size ends

            Route::name('product.')->prefix('product')->group(function () {
                Route::get('/', 'ProductController@index')->name('index');
                Route::get('/create', 'ProductController@create')->name('create');
                Route::post('/store', 'ProductController@store')->name('store');
                Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
                Route::patch('/update/{id}', 'ProductController@update')->name('update');
                Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
                Route::post('/update/status', 'ProductController@status')->name('status');
                Route::post('/update/featured', 'ProductController@featured')->name('featured');
                Route::get('/delete-image/{albumName}/{photoName}', 'ProductController@delete_gallery_image');

                Route::name('variation.')->group(function () {
                    Route::get('/color-and-sizes/{slug}', 'ProductController@variation')->name('index');
                    Route::get('/add-color-and-sizes/{slug}', 'ProductController@addVariationForm')->name('create');
                    Route::post('/add-color-and-sizes/{slug}', 'ProductController@addVariation')->name('store');
                    Route::get('/edit-color-and-sizes/{slug}/{id}', 'ProductController@editVariation')->name('edit');
                    Route::patch('/update-color-and-sizes/{slug}/{id}', 'ProductController@updateVariation')->name('update');
                    Route::get('/color-and-sizes/{slug}/delete/{id}', 'ProductController@deleteVariation')->name('delete');
                    Route::get('/delete-variation-image/{id}/{photoName}', 'ProductController@delete_variation_image');
                });
            });

            Route::name('faq.')->prefix('faq')->group(function () {
                Route::get('/', 'FaqController@index')->name('index');
                Route::post('/set_order', 'FaqController@set_order')->name('order');
                Route::post('/store', 'FaqController@store')->name('store');
                Route::get('/edit/{id}', 'FaqController@edit')->name('edit');
                Route::post('/update/{id}', 'FaqController@update')->name('update');
                Route::get('/delete/{id}', 'FaqController@destroy')->name('destroy');
            });

            Route::name('blog.')->prefix('blog')->group(function () {
                Route::get('/', 'BlogController@index')->name('index');
                Route::get('/create', 'BlogController@create')->name('create');
                Route::post('/store', 'BlogController@store')->name('store');
                Route::get('/edit/{id}', 'BlogController@edit')->name('edit');
                Route::post('/update/{id}', 'BlogController@update')->name('update');
                Route::get('/delete/{id}', 'BlogController@destroy')->name('destroy');
                Route::post('/update/status', 'BlogController@status')->name('status');
            });

            Route::get('/terms-and-condition', 'TermsController@index')->name('terms');
            Route::post('/terms-and-condition/update', 'TermsController@update')->name('terms.update');

            Route::get('/policy', 'PolicyController@index')->name('policy');
            Route::post('/policy/update', 'PolicyController@update')->name('policy.update');
        });
    });
});

app/Models/Size.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Size extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/SizeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Size;
use Illuminate\Support\Facades\DB;

class SizeController extends Controller
{
    public function index()
    {
        $sizes = Size::orderBy('order_item')->get();
        return view('admin.size.index', compact('sizes'));
    }

    public function set_order(Request $request)
    {    
        $list_order = [];
        $size = new Size;

        $list_order = $request['list_order'];
        $i = 1;
        foreach ($list_order as $id) {
            $updateData = array("order_item" => $i);
            Size::where('id', $id)->update($updateData);
            $i++;
        }
        $data = array('status' => 'success');
        return json_encode($data);
    }
    

    public function store(Request $request)
    {
        $this->validate($request, [
            "title" => 'required|max:255',
            "code" => 'required|max:255'
        ]);
        $size = new Size();
		$max_order = DB::table('sizes')->max('order_item');
		$size->title = $request->title;
		$size->code = $request->code;
        $size->order_item = $max_order + 1;

		$size->created_by = auth()->user()->name;
		$size->updated_by = auth()->user()->name;

		$size->save();

        return redirect(route('admin.size.index'))->with('status', 'Size Added Successfully!');
    }

    public function edit($id)
    {
        $size = Size::findOrFail(base64_decode($id));
        return view('admin.size.edit', compact('size'));
    }

    public function update(SizeRequest $request, $id)
    {       
        $this->validate($request, [
            "title" => 'required|max:255',
            "code" => 'required|max:255'
        ]);
        $size = Size::findOrFail(base64_decode($id));
        $size->title = $request->title;
        $size->code = $request->code;

		$size->updated_by = auth()->user()->name;
  
        $size->update();
    	return redirect(route('admin.size.index'))->with('status', 'Size Updated Successfully!');
    }


    public function destroy($id)
    {
        $size = Size::findOrFail(base64_decode($id));      
        $size->delete();

        return redirect()->back()->with('status', 'Size Deleted Successfully!');
    }
}

resources/views/admin/size/edit.blade.php
@extends('admin/layouts.headersidebar')
@section('style')
<link rel="stylesheet" href="{{ asset('backend/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css') }}">
@endsection
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>Sizes</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.size.index') }}">Sizes</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Edit</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ route('admin.size.index') }}" class="btn btn-sm btn-primary" title=""><i
                                class="fa fa-list"></i> Show Sizes</a>
                </div>
            </div>
        </div>
        <div class="card clearfix">
            <div class="card-body">
                <form method="post" action="{{ route('admin.size.update', base64_encode($size->id)) }}" enctype="multipart/form-data">
                    @csrf
                    @method("PATCH")
                    <div class="row">
                        <div class="col-md-6">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-default"><i
                                    class="fa fa-text-width fa-lg"></i> &nbsp;Title</span>
                                </div>
                                <input type="text" name="title" class="form-control"
                                        aria-label="Default" value="{{ isset($size->title) ? $size->title : '' }}"
                                        aria-describedby="inputGroup-sizing-default" required>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-default"><i
                                    class="fa fa-text-width fa-lg"></i> &nbsp;Code</span>
                                </div>
                                <input type="text" name="code" class="form-control"
                                        aria-label="Default" value="{{ isset($size->code) ? $size->code : '' }}"
                                        aria-describedby="inputGroup-sizing-default" required>
                            </div>
                        </div>


                        <div class="clearfix"></div>

                        <div class="col-md-12">
                            <a href="{{ route('admin.size.index') }}"
                                class="btn btn-outline-danger">Cancel</a>

                            <button type="submit" style="float: right;" class="btn btn-outline-success">
                                save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
@endsection

resources/views/admin/size/index.blade.php
@extends('admin/layouts.headersidebar')
@section('style')
    <link rel="stylesheet" href="{{ asset('backend/assets/vendor/nestable/jquery-nestable.css') }}"/>
    <link rel="stylesheet" href="{{ asset('backend/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css') }}">
@endsection
@section('content')
    <script>
        $(document).ready(function () {
            var updateOutput = function (e) {
                var list = e.length ? e : $(e.target), output = list.data('output');

                $.ajax({
                    method: "POST",
                    url: "{{route('admin.size.order')}}",
                    data: {
                        '_token': $('input[name=_token]').val(),
                        list_order: list.nestable('serialize'),
                        table: "sizes"
                    },
                    success: function (response) {
                        var obj = jQuery.parseJSON(response);
                        if (obj.status == 'success') {
                            swal({
                                title: 'Success!',
                                buttonsStyling: false,
                                confirmButtonClass: "btn btn-success",
                                html: '<b>Sizes</b> Sorted Successfully',
                                timer: 1000,
                                type: "success"
                            }).catch(swal.noop);
                        }
                        ;

                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    sweetAlert('Failure', 'Something Went Wrong!', 'error');
                });
            };

            $('#nestable').nestable({
                group: 1,
                maxDepth: 1,
            }).on('change', updateOutput);
        });
    </script>

    <?php
    function displayList($categories)
    {
    ?>
    <ol class="dd-list">
        <?php foreach ($categories as $item): ?>
        <li class="dd-item dd3-item" data-id="{{ $item->id }} ">
            <div class="dd-handle dd3-handle"></div>
            <div class="dd3-content">
                <small>
                    <b>{{ $item->title }}</b>&nbsp;/
                    <small>
                        <b>{{ $item->code }}</b>
                    </small>
                </small>
                <span class="content-right">
                    <a href="{{ route('admin.size.edit', base64_encode($item->id)) }}"
                       class="btn btn-sm btn-outline-primary" title="Edit"><i class="fa fa-edit"></i></a>
                    <a href="#delete"
                       data-toggle="modal"
                       data-id="{{ base64_encode($item->id) }}"
                       id="delete{{ base64_encode($item->id) }}"
                       class="btn btn-sm btn-outline-danger center-block"
                       onClick="delete_menu('{{ base64_encode($item->id) }}')"><i class="fa fa-trash  "></i></a>
                </span>
        </div>
        </li>
        <?php
        endforeach; ?>
    </ol>
    <?php
    }
    ?>

    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h2>Sizes</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item active" aria-current="page"> Manage your sizes</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ url('admin') }}" class="btn btn-outline-primary btn-round"><i
                                class="fa fa-angle-double-left"></i> Go Back</a>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-12">
                <ul class="nav nav-tabs">
                    <li class="nav-item"><a class="nav-link show  active" data-toggle="tab" href="#Pages">All
                            Sizes</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#addPage">Add Size</a></li>
                </ul>
                <div class="tab-content mt-0">
                    <div class="tab-pane show active" id="Pages">
                        <div class="card">
                            <div class="header card-header">
                                <h6 class="title mb-0">All Sizes</h6>
                            </div>
                            <div class="body mt-0">
                                <div class="dd nestable-with-handle" id="nestable">
                                    <?php isset($sizes) ? displayList($sizes) : '' ?>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane" id="addPage">
                        <div class="card">
                            <div class="header card-header">
                                <h6 class="title mb-0">Add Size</h6>
                            </div>
                            <div class="body mt-2">
                                <form method="post" action="{{ route('admin.size.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text" id="inputGroup-sizing-default"><i
                                                    class="fa fa-text-width fa-lg"></i> &nbsp;Title</span>
                                                </div>
                                                <input type="text" name="title" class="form-control"
                                                       aria-label="Default"
                                                       aria-describedby="inputGroup-sizing-default" required>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text" id="inputGroup-sizing-default"><i
                                                    class="fa fa-text-width fa-lg"></i> &nbsp;Code</span>
                                                </div>
                                                <input type="text" name="code" class="form-control"
                                                       aria-label="Default"
                                                       aria-describedby="inputGroup-sizing-default" required>
                                            </div>
                                        </div>

                                        <div class="clearfix"></div>

                                        <div class="col-md-12">
                                            <a href="{{ route('admin.size.index') }}"
                                               class="btn btn-outline-danger">Cancel</a>

                                            <button type="submit" style="float: right;" class="btn btn-outline-success">
                                                save
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog " role="document">
                <div class="modal-content bg-danger">
                    <div class="modal-header">
                        <h5 class="modal-title text-white" id="exampleModalLabel">Delete Size</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-white">
                        <p>Are you Sure...!!</p>
                    </div>
                    <div class="modal-footer ">
                        <button type="button" class="btn btn-round btn-default" data-dismiss="modal">Close</button>
                        <a href="" class="btn btn-round btn-primary">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{ asset('backend/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js') }}"></script><!-- Bootstrap Tags Input Plugin Js --> 
    <script>
        function delete_menu(id) {
            var conn = './size/delete/' + id;
            $('#delete a').attr("href", conn);
        }
    </script>
    <script src="{{ asset('backend/assets/vendor/nestable/jquery.nestable.js') }}"></script><!-- Jquery Nestable -->
    <script src="{{ asset('backend/html/assets/js/pages/ui/sortable-nestable.js') }}"></script>
@endsection