routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::controller(WelcomeController::class)->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    Route::get('product/{slug}', 'product')->name('product');
    Route::get('shop', 'shop')->name('shop');
    Route::post('product/variation-info', 'variation')->name('product.variation');
});
Route::namespace('App\Http\Controllers')->group(function () {

    Route::get('admin/login', 'Auth\LoginController@loginForm')->name('login');
    Route::post('securelogin', 'Auth\LoginController@login')->name('securelogin');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => ['auth']], function () {
        Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');

            // Setting Routes
            Route::get('/setting', 'SettingController@index')->name('setting');
            Route::post('/setting/update', 'SettingController@update')->name('setting.update');
            // Setting Routes end

            //  Users Route
            Route::name('users.')->prefix('users')->group(function () {
                Route::get('/', 'UserController@index')->name('index');
                Route::get('/customer', 'UserController@customer')->name('customer');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/', 'UserController@store')->name('store');
                Route::get('/{id}/show', 'UserController@show')->name('show');
                Route::get('/{id}/edit', 'UserController@edit')->name('edit');
                Route::patch('/{id}', 'UserController@update')->name('update');
                Route::get('/delete/{id}', 'UserController@destroy')->name('destroy');
            });
            //  Users Route End

            Route::name('slider.')->prefix('slider')->group(function () {
                Route::get('/', 'SliderController@index')->name('index');
                Route::post('/set_order', 'SliderController@set_order')->name('order');
                Route::post('/store', 'SliderController@store')->name('store');
                Route::get('/edit/{id}', 'SliderController@edit')->name('edit');
                Route::post('/update/{id}', 'SliderController@update')->name('update');
                Route::get('/delete/{id}', 'SliderController@destroy')->name('destroy');
            });

            Route::name('category.')->prefix('category')->group(function () {
                Route::get('/', 'CategoryController@index')->name('index');
                Route::post('/set_order', 'CategoryController@set_order')->name('order');
                Route::post('/store', 'CategoryController@store')->name('store');
                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('/update/{id}', 'CategoryController@update')->name('update');
                Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
            });

            Route::name('brand.')->prefix('brand')->group(function () {
                Route::get('/', 'BrandController@index')->name('index');
                Route::post('/set_order', 'BrandController@set_order')->name('order');
                Route::post('/store', 'BrandController@store')->name('store');
                Route::get('/edit/{id}', 'BrandController@edit')->name('edit');
                Route::post('/update/{id}', 'BrandController@update')->name('update');
                Route::get('/delete/{id}', 'BrandController@destroy')->name('destroy');
            });

            // Size Chart
            Route::name('sizechart.')->prefix('sizechart')->group(function () {
                Route::get('/', 'SizeChartController@index')->name('index');
                Route::post('/set_order', 'SizeChartController@set_order')->name('order');
                Route::post('/store', 'SizeChartController@store')->name('store');
                Route::get('/edit/{id}', 'SizeChartController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeChartController@update')->name('update');
                Route::get('/delete/{id}', 'SizeChartController@destroy')->name('destroy');
            });
            // Size chart end

            // Size
            Route::name('size.')->prefix('size')->group(function () {
                Route::get('/', 'SizeController@index')->name('index');
                Route::post('/set_order', 'SizeController@set_order')->name('order');
                Route::post('/store', 'SizeController@store')->name('store');
                Route::get('/edit/{id}', 'SizeController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeController@update')->name('update');
                Route::get('/delete/{id}', 'SizeController@destroy')->name('destroy');
            });
            // Size ends

            Route::name('product.')->prefix('product')->group(function () {
                Route::get('/', 'ProductController@index')->name('index');
                Route::get('/create', 'ProductController@create')->name('create');
                Route::post('/store', 'ProductController@store')->name('store');
                Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
                Route::patch('/update/{id}', 'ProductController@update')->name('update');
                Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
                Route::post('/update/status', 'ProductController@status')->name('status');
                Route::post('/update/featured', 'ProductController@featured')->name('featured');
                Route::get('/delete-image/{albumName}/{photoName}', 'ProductController@delete_gallery_image');

                Route::name('variation.')->group(function () {
                    Route::get('/color-and-sizes/{slug}', 'ProductController@variation')->name('index');
                    Route::get('/add-color-and-sizes/{slug}', 'ProductController@addVariationForm')->name('create');
                    Route::post('/add-color-and-sizes/{slug}', 'ProductController@addVariation')->name('store');
                    Route::get('/edit-color-and-sizes/{slug}/{id}', 'ProductController@editVariation')->name('edit');
                    Route::patch('/update-color-and-sizes/{slug}/{id}', 'ProductController@updateVariation')->name('update');
                    Route::get('/color-and-sizes/{slug}/delete/{id}', 'ProductController@deleteVariation')->name('delete');
                    Route::get('/delete-variation-image/{id}/{photoName}', 'ProductController@delete_variation_image');
                });
            });

            Route::name('faq.')->prefix('faq')->group(function () {
                Route::get('/', 'FaqController@index')->name('index');
                Route::post('/set_order', 'FaqController@set_order')->name('order');
                Route::post('/store', 'FaqController@store')->name('store');
                Route::get('/edit/{id}', 'FaqController@edit')->name('edit');
                Route::post('/update/{id}', 'FaqController@update')->name('update');
                Route::get('/delete/{id}', 'FaqController@destroy')->name('destroy');
            });

            Route::name('blog.')->prefix('blog')->group(function () {
                Route::get('/', 'BlogController@index')->name('index');
                Route::get('/create', 'BlogController@create')->name('create');
                Route::post('/store', 'BlogController@store')->name('store');
                Route::get('/edit/{id}', 'BlogController@edit')->name('edit');
                Route::post('/update/{id}', 'BlogController@update')->name('update');
                Route::get('/delete/{id}', 'BlogController@destroy')->name('destroy');
                Route::post('/update/status', 'BlogController@status')->name('status');
            });

            Route::get('/terms-and-condition', 'TermsController@index')->name('terms');
            Route::post('/terms-and-condition/update', 'TermsController@update')->name('terms.update');

            Route::get('/policy', 'PolicyController@index')->name('policy');
            Route::post('/policy/update', 'PolicyController@update')->name('policy.update');
        });
    });
});

app/Models/Policy.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Policy extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/PolicyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Policy;
use App\Models\CropImg;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;

class PolicyController extends Controller
{
    public function index()
    {
        $policy = Policy::findOrFail(1);
        return view('admin.policy.index', compact('policy'));
    }

    public function update(Request $request)
    {
        $this->validate($request, [
            'content' => 'required'
        ]);

        $policy = Policy::findOrFail(1);
        $policy->content = $request->content;
        $policy->update();
        
        return redirect(route('admin.policy'))->with('status', 'Policy content updated successfully');
    }
}

resources/views/admin/policy/form.blade.php
@extends('admin/layouts.headersidebar')
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>Policies</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('admin.policy.index') }}">Policies</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">{{ isset($item) ? 'Update' : 'Create' }}</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ route('admin.policy.index') }}" class="btn btn-sm btn-primary" title=""><i
                                class="fa fa-list"></i> Show policy</a>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-12">
                @php
                    $url = route('admin.policy.store');
                if (isset($item)){
                    $url = route('admin.policy.update', $item->slug);
                }
                @endphp
                <form method="POST" action="{{ $url }}" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">Title</span>
                                        </div>
                                        <input type="text" class="form-control" name="title"
                                               placeholder="Title" value="{{isset($item->title)? $item->title:''}}"
                                               aria-label="Title"
                                               aria-describedby="basic-addon1" required>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <input type="checkbox" name="status" {{isset($item->status) && $item->status == 1 ? 'checked' : ''}} ></span>
                                        </div>
                                        <input type="text" class="form-control" value="Display Status" disabled>
                                    </div>
                                </div>

                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="card">
                                        <div class="card-header">Description</div>
                                        <div class="body">
                                            <textarea id="ckeditor" name="description">
                                                {!! isset($item->description) ? $item->description:'' !!}
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <a href="{{ route('admin.policy.index') }}" class="btn btn-danger">Cancel</a>
                                <span class="float-right">
                                <button type="submit" name="submit" class="btn btn-success" value="save">Save</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script src="https://cdn.ckeditor.com/4.14.1/full/ckeditor.js"></script>
    <script>
            CKEDITOR.replace( 'ckeditor' );
    </script>
@endsection

resources/views/admin/policy/index.blade.php
@extends('admin/layouts.headersidebar')
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>Policies</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Policy Update</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-12">
                <form method="POST" action="{{ route('admin.policy.update') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                    <div class="body">
                            <div class="row">

                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="card">
                                        <div class="card-header">Content</div>
                                        <div class="body">
                                            <textarea id="ckeditor" name="content">
                                                {!! isset($policy->content) ? $policy->content:'' !!}
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" name="submit" class="btn btn-success" value="save">Save</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script src="https://cdn.ckeditor.com/4.14.1/full/ckeditor.js"></script>
    <script>
            CKEDITOR.replace( 'ckeditor' );
    </script>
@endsection