routes/web.php
<?php

use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::controller(WelcomeController::class)->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    Route::get('product/{slug}', 'product')->name('product');
    Route::get('shop', 'shop')->name('shop');
    Route::post('product/variation-info', 'variation')->name('product.variation');
});
Route::namespace('App\Http\Controllers')->group(function () {

    Route::get('admin/login', 'Auth\LoginController@loginForm')->name('login');
    Route::post('securelogin', 'Auth\LoginController@login')->name('securelogin');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => ['auth']], function () {
        Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');

            // Setting Routes
            Route::get('/setting', 'SettingController@index')->name('setting');
            Route::post('/setting/update', 'SettingController@update')->name('setting.update');
            // Setting Routes end

            //  Users Route
            Route::name('users.')->prefix('users')->group(function () {
                Route::get('/', 'UserController@index')->name('index');
                Route::get('/customer', 'UserController@customer')->name('customer');
                Route::get('/create', 'UserController@create')->name('create');
                Route::post('/', 'UserController@store')->name('store');
                Route::get('/{id}/show', 'UserController@show')->name('show');
                Route::get('/{id}/edit', 'UserController@edit')->name('edit');
                Route::patch('/{id}', 'UserController@update')->name('update');
                Route::get('/delete/{id}', 'UserController@destroy')->name('destroy');
            });
            //  Users Route End

            Route::name('slider.')->prefix('slider')->group(function () {
                Route::get('/', 'SliderController@index')->name('index');
                Route::post('/set_order', 'SliderController@set_order')->name('order');
                Route::post('/store', 'SliderController@store')->name('store');
                Route::get('/edit/{id}', 'SliderController@edit')->name('edit');
                Route::post('/update/{id}', 'SliderController@update')->name('update');
                Route::get('/delete/{id}', 'SliderController@destroy')->name('destroy');
            });

            Route::name('category.')->prefix('category')->group(function () {
                Route::get('/', 'CategoryController@index')->name('index');
                Route::post('/set_order', 'CategoryController@set_order')->name('order');
                Route::post('/store', 'CategoryController@store')->name('store');
                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                Route::post('/update/{id}', 'CategoryController@update')->name('update');
                Route::get('/delete/{id}', 'CategoryController@destroy')->name('destroy');
            });

            Route::name('brand.')->prefix('brand')->group(function () {
                Route::get('/', 'BrandController@index')->name('index');
                Route::post('/set_order', 'BrandController@set_order')->name('order');
                Route::post('/store', 'BrandController@store')->name('store');
                Route::get('/edit/{id}', 'BrandController@edit')->name('edit');
                Route::post('/update/{id}', 'BrandController@update')->name('update');
                Route::get('/delete/{id}', 'BrandController@destroy')->name('destroy');
            });

            // Size Chart
            Route::name('sizechart.')->prefix('sizechart')->group(function () {
                Route::get('/', 'SizeChartController@index')->name('index');
                Route::post('/set_order', 'SizeChartController@set_order')->name('order');
                Route::post('/store', 'SizeChartController@store')->name('store');
                Route::get('/edit/{id}', 'SizeChartController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeChartController@update')->name('update');
                Route::get('/delete/{id}', 'SizeChartController@destroy')->name('destroy');
            });
            // Size chart end

            // Size
            Route::name('size.')->prefix('size')->group(function () {
                Route::get('/', 'SizeController@index')->name('index');
                Route::post('/set_order', 'SizeController@set_order')->name('order');
                Route::post('/store', 'SizeController@store')->name('store');
                Route::get('/edit/{id}', 'SizeController@edit')->name('edit');
                Route::patch('/update/{id}', 'SizeController@update')->name('update');
                Route::get('/delete/{id}', 'SizeController@destroy')->name('destroy');
            });
            // Size ends

            Route::name('product.')->prefix('product')->group(function () {
                Route::get('/', 'ProductController@index')->name('index');
                Route::get('/create', 'ProductController@create')->name('create');
                Route::post('/store', 'ProductController@store')->name('store');
                Route::get('/edit/{id}', 'ProductController@edit')->name('edit');
                Route::patch('/update/{id}', 'ProductController@update')->name('update');
                Route::get('/delete/{id}', 'ProductController@destroy')->name('destroy');
                Route::post('/update/status', 'ProductController@status')->name('status');
                Route::post('/update/featured', 'ProductController@featured')->name('featured');
                Route::get('/delete-image/{albumName}/{photoName}', 'ProductController@delete_gallery_image');

                Route::name('variation.')->group(function () {
                    Route::get('/color-and-sizes/{slug}', 'ProductController@variation')->name('index');
                    Route::get('/add-color-and-sizes/{slug}', 'ProductController@addVariationForm')->name('create');
                    Route::post('/add-color-and-sizes/{slug}', 'ProductController@addVariation')->name('store');
                    Route::get('/edit-color-and-sizes/{slug}/{id}', 'ProductController@editVariation')->name('edit');
                    Route::patch('/update-color-and-sizes/{slug}/{id}', 'ProductController@updateVariation')->name('update');
                    Route::get('/color-and-sizes/{slug}/delete/{id}', 'ProductController@deleteVariation')->name('delete');
                    Route::get('/delete-variation-image/{id}/{photoName}', 'ProductController@delete_variation_image');
                });
            });

            Route::name('faq.')->prefix('faq')->group(function () {
                Route::get('/', 'FaqController@index')->name('index');
                Route::post('/set_order', 'FaqController@set_order')->name('order');
                Route::post('/store', 'FaqController@store')->name('store');
                Route::get('/edit/{id}', 'FaqController@edit')->name('edit');
                Route::post('/update/{id}', 'FaqController@update')->name('update');
                Route::get('/delete/{id}', 'FaqController@destroy')->name('destroy');
            });

            Route::name('blog.')->prefix('blog')->group(function () {
                Route::get('/', 'BlogController@index')->name('index');
                Route::get('/create', 'BlogController@create')->name('create');
                Route::post('/store', 'BlogController@store')->name('store');
                Route::get('/edit/{id}', 'BlogController@edit')->name('edit');
                Route::post('/update/{id}', 'BlogController@update')->name('update');
                Route::get('/delete/{id}', 'BlogController@destroy')->name('destroy');
                Route::post('/update/status', 'BlogController@status')->name('status');
            });

            Route::get('/terms-and-condition', 'TermsController@index')->name('terms');
            Route::post('/terms-and-condition/update', 'TermsController@update')->name('terms.update');

            Route::get('/policy', 'PolicyController@index')->name('policy');
            Route::post('/policy/update', 'PolicyController@update')->name('policy.update');
        });
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function variations()
    {
        return $this->hasMany(Variation::class);
    }

    protected function createSlug($title, $id = 0)
    {
        // Normalize the title
        $slug = str_slug($title);

        $allSlugs = $this->getRelatedSlugs($slug, $id);

        // If we haven't used it before then we are all good.
        if (!$allSlugs->contains('slug', $slug)) {
            return $slug;
        }

        // Just append numbers like a savage until we find not used.
        for ($i = 1; $i <= 10; $i++) {
            $newSlug = $slug . '-' . $i;
            if (!$allSlugs->contains('slug', $newSlug)) {
                return $newSlug;
            }
        }

        throw new \Exception('Can not create a unique slug');
    }
    protected function getRelatedSlugs($slug, $id = 0)
    {
        return Product::select('slug')->where('slug', 'like', $slug . '%')
            ->where('id', '<>', $id)
            ->get();
    }
}

resources/views/admin/product/index.blade.php
@extends('admin/layouts.headersidebar')
@section('style')
<link rel="stylesheet" href="{{ asset('backend/assets/jquery-datatable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend/assets/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend/assets/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css') }}">
@endsection
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>Products Section</h1>
                    <small>Manage Your Products From Here</small>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Products</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <a href="{{ route('admin.product.create') }}" class="btn btn-primary"><i
                                class="fa fa-plus-circle"></i> Create New Product</a>
                </div>
            </div>
        </div>

        <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="header">
                            <ul class="header-dropdown dropdown">
                                
                                <li><a href="javascript:void(0);" class="full-screen"><i class="icon-frame"></i></a></li>
                                
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-hover js-basic-example dataTable table-custom spacing5">
                                    <thead>
                                        <tr>
                                            <th>Image</th>
                                            <th>Code</th>
                                            <th>Category</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Featured</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Image</th>
                                            <th>Code</th>
                                            <th>Category</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Featured</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach($products as $chunked)
                                        @foreach($chunked as $product)
                                        <tr>
                                            <td class="w60">
                                               <div class="avtar-pic w35 bg-red" data-toggle="tooltip" data-placement="top"
                                               title=""
                                               data-original-title="{{ $product->name }}">
                                               <span><img
                                                   src="{{ asset('storage/product/'.$product->slug.'/small_'.$product->image) }}"
                                                   class="img-thumbnail"></span>
                                               </div>
                                            </td>
                                            <td>{{ $product->variation == null ? \Illuminate\Support\Str::limit($product->sku, 15, $end='...') : '' }}</td>

                                            <td>{{ $product->category->title }}</td>
                                            
                                            <td>
                                                <div class="font-16">{{ \Illuminate\Support\Str::limit($product->title, 30, $end='...') }}</div>
                                            </td>
                                            <form action="" id="statusForm">
                                                @if($product->display === 1)
                                                    <td class=""><span><a href="#" onclick="status('{{ $product->id }}')"><i
                                                                        class="fa fa-toggle-on text-success fd"></i></a></span>
                                                    </td>
                                                @else
                                                    <td class=""><span><a href="#" onclick="status('{{ $product->id }}')"><i
                                                                        class="fa fa-toggle-off text-danger fd"></i></a></span>
                                                    </td>
                                                @endif
                                            </form>
                                            <form action="" id="statusForm">
                                                @if($product->featured === 1)
                                                    <td class=""><span><a href="#" onclick="featured('{{ $product->id }}')"><i
                                                                        class="fa fa-toggle-on text-success fd"></i></a></span>
                                                    </td>
                                                @else
                                                    <td class=""><span><a href="#" onclick="featured('{{ $product->id }}')"><i
                                                                        class="fa fa-toggle-off text-danger fd"></i></a></span>
                                                    </td>
                                                @endif
                                            </form>
                                              
                                            <td>
                                                <a href="{{ route('admin.product.variation.index', $product->slug) }}" class="btn btn-outline-info btn-sm" href="">Manage Colors and sizes</a>
                                                <a class="btn btn-outline-success btn-sm" href="{{ route('admin.product.edit', $product->id) }}"><i class="fa fa-edit"></i></a>
                                                <a class="btn btn-outline-danger btn-sm" href="#delete" data-toggle="modal" onclick="delete_product('<?= basename($product->id); ?>')"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                        @endforeach
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
            </div>
    </div>


<div class="modal modal-primary fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you want to delete product?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-round btn-outline-primary" data-dismiss="modal">Close</a>
                <a class="btn btn-round btn-danger" href="">Delete It!</a>
            </div>
        </div>
    </div>
</div>


@endsection
@section('script')
<script src="{{ asset('backend/assets/jquery-datatable.js') }}"></script>
<script src="{{ asset('backend/assets/jquery-datatable/buttons/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('backend/assets/jquery-datatable/buttons/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('backend/assets/datatablescripts.bundle.js') }}"></script>
    <script>
        function status(id) {
            $.ajax({
                method: 'POST',
                url: "{{ route('admin.product.status') }}",
                data: {
                    '_token': $('input[name=_token]').val(),
                    'id': id
                },
                success: function (response) {
                    var obj = jQuery.parseJSON(response);
                    if (obj.success) {
                        toastr.success(obj.success);
                        setTimeout(function () {
                            location.reload();  //Refresh page
                        }, 100);
                    } else if (obj.error) {
                        toastr.error(obj.error);
                    }
                },
                error: function (response){
                    console.log("error",response);
                }
            })
        }

        function featured(id) {
            $.ajax({
                method: 'POST',
                url: "{{ route('admin.product.featured') }}",
                data: {
                    '_token': $('input[name=_token]').val(),
                    'id': id
                },
                success: function (response) {
                    var obj = jQuery.parseJSON(response);
                    if (obj.success) {
                        toastr.success(obj.success);
                        setTimeout(function () {
                            location.reload();  //Refresh page
                        }, 100);
                    } else if (obj.error) {
                        toastr.error(obj.error);
                    }
                },
                error: function (response){
                    console.log("error",response);
                }
            })
        }

        function delete_product(medium) {
            // alert(file);
            var conn = '/admin/product/delete/' + medium;
            $('#delete a').attr("href", conn);
        }
    </script>
   
@endsection

resources/views/admin/product/variation.blade.php
@extends('admin/layouts.headersidebar')
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>Products Color & Size Section</h1>
                    <small>Manage Your Products From Here</small>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                            <li class="breadcrumb-item" aria-current="page"><a
                                    href="{{ route('admin.product.index') }}">Products</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Colors & Sizes</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <a href="{{ route('admin.product.variation.create', $slug) }}" class="btn btn-primary"><i
                            class="fa fa-plus-circle"></i> Add Colors and Sizes</a>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <ul class="header-dropdown dropdown">

                            <li><a href="javascript:void(0);" class="full-screen"><i class="icon-frame"></i></a></li>

                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5">
                                <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Color</th>
                                        <th>Sizes</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Color</th>
                                        <th>Sizes</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @foreach ($variations as $variation)
                                        {{-- @dd($variation) --}}
                                        <tr>
                                            <td class="w60">
                                                <div class="avtar-pic w35 bg-red" data-toggle="tooltip" data-placement="top"
                                                    title="" data-original-title="">
                                                    <span><img
                                                            src="{{ asset('storage/product/' . $variation->product->slug . '/' . substr($variation->color_code, 1) . '/small_' . $variation->image) }}"
                                                            class="img-thumbnail"></span>
                                                </div>
                                            </td>
                                            <td>{{ $variation->title }}</td>
                                            <td class="w60">
                                                <div class="avtar-pic w35" data-toggle="tooltip" data-placement="top"
                                                    title="" style="background-color:{{ $variation->color_code }}">
                                                </div>
                                            </td>
                                            <?php $sizes =
                                                $variation->sizes !== null
                                                    ? App\Models\Size::whereIn('id', json_decode($variation->sizes))
                                                        ->select('code')
                                                        ->get()
                                                    : ''; ?>
                                            <td>
                                                @foreach ($sizes as $key => $size)
                                                    {{ $size->code }} @if (count($sizes) > 1 && $key < count($sizes))
                                                        ,
                                                    @endif
                                                @endforeach
                                            </td>
                                            <td>
                                                <a class="btn btn-outline-success btn-sm"
                                                    href="{{ route('admin.product.variation.edit', ['slug' => $slug, 'id' => base64_encode($variation->id)]) }}"><i
                                                        class="fa fa-edit"></i></a>
                                                <a class="btn btn-outline-danger btn-sm" href="#delete" data-toggle="modal"
                                                    onclick="delete_product('{{ $slug }}', '<?= base64_encode($variation->id) ?>')"><i
                                                        class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="modal modal-primary fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Variation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Do you want to delete variation?</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-round btn-outline-primary" data-dismiss="modal">Close</a>
                    <a class="btn btn-round btn-danger" href="">Delete It!</a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        function delete_product(slug, medium) {
            // alert(file);
            var conn = '/admin/product/color-and-sizes/' + slug + '/delete/' + medium;
            $('#delete a').attr("href", conn);
        }
    </script>
@endsection